version: '3.8'

services:
  ms-sistema-app:
    image: openjdk:20-jdk-slim
    container_name: ms-sistema
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ms-sistema-db:5432/ms-sistema-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8080"
    depends_on:
      - ms-sistema-db
    networks:
      - saude-network
    volumes:
      - ./target/ms-sistema.jar:/ms-sistema.jar
    command: ["java", "-jar", "/ms-sistema.jar"]

  ms-sistema-db:
    image: postgres:latest
    container_name: ms-sistema-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ms-sistema-db
    ports:
      - "5436:5432"
    volumes:
      - postgres_sistema_data:/var/lib/postgresql/data
    networks:
      - saude-network

volumes:
  postgres_sistema_data:

networks:
  saude-network:
    driver: bridge
